name: Build

on:
  workflow_call:
    inputs:
      python-version:
        description: Python version
        type: string
        required: true
      runner:
        description: Runner label
        type: string
        required: true

permissions:
  contents: read  # Read repository contents

jobs:
  build:
    name: Python ${{ inputs.python-version }} (${{ inputs.runner }})
    runs-on: ${{ inputs.runner }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-tags: 0

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install uv
        run: |
          python3 -m pip install --user pipx
          python3 -m pipx ensurepath
          pipx install uv

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        run: task test

      - name: Build package
        run: task build

      - name: Upload build artifacts
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: python-package-${{ inputs.python-version }}-${{ inputs.runner }}
          path: dist/
          retention-days: 1
